### ISSUE TITLE
TL;DR

### ISSUE THREAD

**Issue by oliviertassinari** [alitaheri/react-memo#1]
Just to be clear. 
I'm right discribing `react-memo` as a standalone version of [`reselect`](https://github.com/reactjs/reselect)  (independant of `react-redux`) :heart_eyes:?

**Comment by alitaheri** [comment]
:laughing: :laughing: 

Actually reselect works with redux's singular state tree (single store). This will only take props and context and pass down new porps. It's only used as a cache with invalidation logic that is the value selectors. I hope that clarifies O.o Maybe I should Add TL;DR section too :+1: :+1:
